name: Build and Release PDF

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive-full

     
      - name: Build PDF
        run: |
          mkdir -p output
          pdflatex -output-directory=output main.tex

     
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: output/main.pdf

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3

     
      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-pdf

     
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: output/main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
